
# -*- coding: utf-8 -*-
#
# -----------------------------------------------------------------------------
# switch.py - Alpaca API responders for Switch
#
# Author:   Jakob Kästner (kae)
#
# -----------------------------------------------------------------------------
# Edit History:
#   Generated by Python Interface Generator for AlpycaDevice
#
# 16-Feb-2026   kae 0.1 initial implementation
import datetime
from types import MethodDescriptorType, ModuleType
from requests.models import DecodeError
from typing_extensions import KeysView
from falcon import Request, Response, HTTPBadRequest, before
from logging import Logger
from shr import PropertyResponse, MethodResponse, PreProcessRequest, \
                StateValue, get_request_field, to_bool
from exceptions import *        # Nothing but exception classes

# DRIVER
import smartplug_driver.epower_smart_plug as epower_smart_plug
import smartplug_driver.intertech_smart_plug as intertech_smart_plug

# ----------------------
# MULTI-INSTANCE SUPPORT
# ----------------------
# If this is > 0 then it means that multiple devices of this type are supported.
# Each responder on_get() and on_put() is called with a devnum parameter to indicate
# which instance of the device (0-based) is being called by the client. Leave this
# set to 0 for the simple case of controlling only one instance of this device type.
#
maxdev = len(Config.smartplugs) - 1

# -----------
# DEVICE INFO
# -----------
# Static metadata not subject to configuration changes
#
class SwitchMetadata:
    """ This driver controls one/multiple smart plugs (specified in config.toml)"""
    Name = '[device] driver'
    Version = '0.1'
    Description = 'Alpaca switch controlling smart plugs'
    DeviceType = 'Switch'
    DeviceID = 'bfdcfd5a-3da2-4899-97a5-48ce1caba612' # https://guidgenerator.com/online-guid-generator.aspx
    Info = 'Alpaca Switch\nImplements ISwitchV3\n'
    MaxDeviceNumber = maxdev
    InterfaceVersion = 3       # ISwitchVxxx

# --------------------
# INIT & GLOBALS
# --------------------

logger: Logger = None
is_connected = [False for _ in range(len(Config.smartplugs))]

supported_devices = {
    "epower" : epower_smart_plug,
    "intertech" : intertech_smart_plug
}

# quasi init function
def start_switch_device(logger_instance: Logger):
    global logger
    logger = logger_instance

    success = True
    for device in Config.smartplugs:
        if device["driver"] not in supported_devices.keys():
            success = False
            print(f"ERROR: '{device["driver"]}' specified in config.toml, is not in supported_devices: {supported_devices}")

    if success:
       print("ERROR: cannot start switch due to fatal error!")

    return success

# ----------------------
# CONFIG HELPER
# ----------------------

def get_device_addr(devnum: int) -> str:
    return Config.smartplugs[devnum]["addr"]

def get_device_name(devnum: int) -> str:
    return Config.smartplugs[devnum]["name"]

def get_device_size(devnum: int) -> int:
    return len(Config.smartplugs[devnum]["outlet"])

def get_device_switch_description(devnum: int, switch_id: int) -> str:
    return Config.smartplugs[devnum]["outlet"][switch_id]["description"]

def get_device_switch_name(devnum: int, switch_id: int) -> str:
    return Config.smartplugs[devnum]["outlet"][switch_id]["name"]

def set_device_switch_name(devnum: int, switch_id: int, name: str) -> None:
    Config.smartplugs[devnum]["outlet"][switch_id]["name"] = name

def set_device_switch_description(devnum: int, switch_id: int, description: str) -> None:
    Config.smartplugs[devnum]["outlet"][switch_id]["description"] = description

def get_device_driver(devnum: int) -> ModuleType:
    return supported_devices[Config.smartplugs[devnum]["driver"]]

# ------------
# OTHER HELPER
# ------------

def id_is_in_bounds(req: Request, resp: Response, devnum: int, id: int, err_message="Switch index is out of bounds"):
    if 0 <= id < get_device_size(devnum):
        return True

    if req.method.upper() == "GET":
        resp.text = PropertyResponse(None, req,
                        InvalidValueException(err_message)).json
    elif req.method.upper() == "PUT":
        resp.text = MethodResponse(req,
                        InvalidValueException(err_message), None).json
    else:
        logger.error(f"req.method was neither GET or PUT", req.method)

    return False


def get_id(req: Request, resp: Response):
    idstr = get_request_field('Id', req)      # Raises 400 bad request if missing
    try:
        id = int(idstr)
    except:
        if req.method.upper() == "GET":
            resp.text = PropertyResponse(None, req,
                            InvalidValueException(f'Id {idstr} not a valid integer.')).json
        elif req.method.upper() == "PUT":
            resp.text = MethodResponse(req,
                            InvalidValueException(f'Id {idstr} not a valid integer.'), None).json
        else:
            logger.error("req.method was neither GET or PUT")

        return None
    return id


def get_id_and_bounds_check(req: Request, resp: Response, devnum):
    id = get_id(req, resp)
    if id is None:
        return id

    return id if id_is_in_bounds(req, resp, devnum, id) else None


# --------------------
# RESOURCE CONTROLLERS
# --------------------

@before(PreProcessRequest(maxdev))
class action:
    def on_put(self, req: Request, resp: Response, devnum: int):
        resp.text = MethodResponse(req, NotImplementedException()).json

@before(PreProcessRequest(maxdev))
class commandblind:
    def on_put(self, req: Request, resp: Response, devnum: int):
        resp.text = MethodResponse(req, NotImplementedException()).json

@before(PreProcessRequest(maxdev))
class commandbool:
    def on_put(self, req: Request, resp: Response, devnum: int):
        resp.text = MethodResponse(req, NotImplementedException()).json

@before(PreProcessRequest(maxdev))
class commandstring:
    def on_put(self, req: Request, resp: Response, devnum: int):
        resp.text = MethodResponse(req, NotImplementedException()).json

@before(PreProcessRequest(maxdev))
class connect:
    def on_put(self, req: Request, resp: Response, devnum: int):
        global is_connected
        try:
            test = get_device_driver(devnum).get_power_status(Config.smartplugs[devnum]["addr"])
            if len(test) == get_device_size(devnum):
                is_connected[devnum] = True
            else:
                # TODO: raise error
                pass

            resp.text = MethodResponse(req).json
        except Exception as ex:
            resp.text = MethodResponse(req,
                            DriverException(0x500, 'Switch.Connect failed', ex)).json

@before(PreProcessRequest(maxdev))
class connected:
    def on_get(self, req: Request, resp: Response, devnum: int):
        global is_connected
        try:
            is_conn = is_connected[devnum]
            resp.text = PropertyResponse(is_conn, req).json
        except Exception as ex:
            resp.text = PropertyResponse(None, req, DriverException(0x500, 'Switch.Connected failed', ex)).json

    def on_put(self, req: Request, resp: Response, devnum: int):
        global is_connected
        conn_str = get_request_field('Connected', req)
        conn = to_bool(conn_str)              # Raises 400 Bad Request if str to bool fails

        try:
            if conn:
                get_device_driver(devnum).get_power_status(Config.smartplugs[devnum]["addr"])
                is_connected[devnum] = True
            else:
                is_connected[devnum] = False

            resp.text = MethodResponse(req).json
        except Exception as ex:
            resp.text = MethodResponse(req, # Put is actually like a method :-(
                            DriverException(0x500, 'Switch.Connected failed', ex)).json

@before(PreProcessRequest(maxdev))
class connecting:
    def on_get(self, req: Request, resp: Response, devnum: int):
        try:
            val = False
            resp.text = PropertyResponse(val, req).json
        except Exception as ex:
            resp.text = PropertyResponse(None, req,
                            DriverException(0x500, 'Switch.Connecting failed', ex)).json

@before(PreProcessRequest(maxdev))
class description:
    def on_get(self, req: Request, resp: Response, devnum: int):
        resp.text = PropertyResponse(SwitchMetadata.Description, req).json

@before(PreProcessRequest(maxdev))
class devicestate:

    def on_get(self, req: Request, resp: Response, devnum: int):
        if not is_connected[devnum]:
            resp.text = PropertyResponse(None, req,
                            NotConnectedException()).json
            return
        try:
            val = list()
            states = get_device_driver(devnum).get_power_status(get_device_addr(devnum))

            for i in range(len(states)):
                val.append(StateValue(f"GetSwitch{i}", float(states[i])))

            for i in range(len(states)):
                val.append(StateValue(f"GetSwitchValue{i}", float(states[i])))

            val.append(StateValue('TimeStamp', datetime.datetime.utcnow().isoformat()))

            resp.text = PropertyResponse(val, req).json
        except Exception as ex:
            resp.text = PropertyResponse(None, req,
                            DriverException(0x500, 'switch.Devicestate failed', ex)).json


@before(PreProcessRequest(maxdev))
class disconnect:
    def on_put(self, req: Request, resp: Response, devnum: int):
        global is_connected
        try:
            if is_connected[devnum]:
                is_connected[devnum] = False

            resp.text = MethodResponse(req).json
        except Exception as ex:
            resp.text = MethodResponse(req, DriverException(0x500, 'Switch.Disconnect failed', ex)).json

@before(PreProcessRequest(maxdev))
class driverinfo:
    def on_get(self, req: Request, resp: Response, devnum: int):
        resp.text = PropertyResponse(SwitchMetadata.Info, req).json

@before(PreProcessRequest(maxdev))
class interfaceversion:
    def on_get(self, req: Request, resp: Response, devnum: int):
        resp.text = PropertyResponse(SwitchMetadata.InterfaceVersion, req).json

@before(PreProcessRequest(maxdev))
class driverversion():
    def on_get(self, req: Request, resp: Response, devnum: int):
        resp.text = PropertyResponse(SwitchMetadata.Version, req).json

@before(PreProcessRequest(maxdev))
class name():
    def on_get(self, req: Request, resp: Response, devnum: int):
        resp.text = PropertyResponse(SwitchMetadata.Name, req).json

@before(PreProcessRequest(maxdev))
class supportedactions:
    def on_get(self, req: Request, resp: Response, devnum: int):
        resp.text = PropertyResponse([], req).json  # Not PropertyNotImplemented

@before(PreProcessRequest(maxdev))
class maxswitch:
    def on_get(self, req: Request, resp: Response, devnum: int):
        global is_connected
        if not is_connected[devnum]:
            resp.text = PropertyResponse(None, req,
                            NotConnectedException()).json
            return

        try:
            val = get_device_size(devnum) #
            resp.text = PropertyResponse(val, req).json
        except Exception as ex:
            resp.text = PropertyResponse(None, req,
                            DriverException(0x500, 'Switch.Maxswitch failed', ex)).json


@before(PreProcessRequest(maxdev))
class canwrite:
    def on_get(self, req: Request, resp: Response, devnum: int):
        if not is_connected[devnum]:
            resp.text = PropertyResponse(None, req,
                            NotConnectedException()).json
            return

        id = get_id_and_bounds_check(req, resp, devnum)
        if id is None:
            return

        try:
            val = True #

            resp.text = PropertyResponse(val, req).json
        except Exception as ex:
            resp.text = PropertyResponse(None, req,
                            DriverException(0x500, 'Switch.Canwrite failed', ex)).json


@before(PreProcessRequest(maxdev))
class getswitch:
    def on_get(self, req: Request, resp: Response, devnum: int):
        if not is_connected[devnum]:
            resp.text = PropertyResponse(None, req,
                            NotConnectedException()).json
            return

        id = get_id_and_bounds_check(req, resp, devnum)
        if id is None:
            return

        try:
            val = get_device_driver(devnum).get_power_status(get_device_addr(devnum))[id] #
            resp.text = PropertyResponse(val, req).json
        except Exception as ex:
            resp.text = PropertyResponse(None, req,
                            DriverException(0x500, 'Switch.Getswitch failed', ex)).json


@before(PreProcessRequest(maxdev))
class getswitchdescription:
    def on_get(self, req: Request, resp: Response, devnum: int):
        if not is_connected[devnum]:
            resp.text = PropertyResponse(None, req,
                            NotConnectedException()).json
            return

        id = get_id_and_bounds_check(req, resp, devnum)
        if id is None:
            return

        try:
            val = get_device_switch_description(devnum, id) #
            resp.text = PropertyResponse(val, req).json
        except Exception as ex:
            resp.text = PropertyResponse(None, req,
                            DriverException(0x500, 'Switch.Getswitchdescription failed', ex)).json


@before(PreProcessRequest(maxdev))
class getswitchname:
    def on_get(self, req: Request, resp: Response, devnum: int):
        if not is_connected[devnum]:
            resp.text = PropertyResponse(None, req,
                            NotConnectedException()).json
            return

        id = get_id_and_bounds_check(req, resp, devnum)
        if id is None:
            return

        try:
            val = get_device_switch_name(devnum, id) #
            resp.text = PropertyResponse(val, req).json
        except Exception as ex:
            resp.text = PropertyResponse(None, req,
                            DriverException(0x500, 'Switch.Getswitchname failed', ex)).json


@before(PreProcessRequest(maxdev))
class getswitchvalue:
    def on_get(self, req: Request, resp: Response, devnum: int):
        if not is_connected[devnum]:
            resp.text = PropertyResponse(None, req,
                            NotConnectedException()).json
            return

        id = get_id_and_bounds_check(req, resp, devnum)
        if id is None:
            return

        try:
            val = float(get_device_driver(devnum).get_power_status(get_device_addr(devnum))[id]) #
            resp.text = PropertyResponse(val, req).json
        except Exception as ex:
            resp.text = PropertyResponse(None, req,
                            DriverException(0x500, 'Switch.Getswitchvalue failed', ex)).json


@before(PreProcessRequest(maxdev))
class minswitchvalue:
    def on_get(self, req: Request, resp: Response, devnum: int):
        if not is_connected[devnum]:
            resp.text = PropertyResponse(None, req,
                            NotConnectedException()).json
            return

        id = get_id_and_bounds_check(req, resp, devnum)
        if id is None:
            return

        try:
            val = 0.0 #
            resp.text = PropertyResponse(val, req).json
        except Exception as ex:
            resp.text = PropertyResponse(None, req,
                            DriverException(0x500, 'Switch.Minswitchvalue failed', ex)).json


@before(PreProcessRequest(maxdev))
class maxswitchvalue:
    def on_get(self, req: Request, resp: Response, devnum: int):
        if not is_connected[devnum]:
            resp.text = PropertyResponse(None, req,
                            NotConnectedException()).json
            return

        id = get_id_and_bounds_check(req, resp, devnum)
        if id is None:
            return

        try:
            val = 1.0 #
            resp.text = PropertyResponse(val, req).json
        except Exception as ex:
            resp.text = PropertyResponse(None, req,
                            DriverException(0x500, 'Switch.Maxswitchvalue failed', ex)).json


@before(PreProcessRequest(maxdev))
class switchstep:
    def on_get(self, req: Request, resp: Response, devnum: int):
        if not is_connected[devnum]:
            resp.text = PropertyResponse(None, req,
                            NotConnectedException()).json
            return

        id = get_id_and_bounds_check(req, resp, devnum)
        if id is None:
            return

        try:
            val = 1.0 #
            resp.text = PropertyResponse(val, req).json
        except Exception as ex:
            resp.text = PropertyResponse(None, req,
                            DriverException(0x500, 'Switch.Switchstep failed', ex)).json


@before(PreProcessRequest(maxdev))
class setswitch:
    def on_put(self, req: Request, resp: Response, devnum: int):
        if not is_connected[devnum]:
            resp.text = MethodResponse(req,
                            NotConnectedException(), None).json
            return

        id = get_id_and_bounds_check(req, resp, devnum)
        if id is None:
            return

        statestr = get_request_field('State', req)      # Raises 400 bad request if missing
        state = to_bool(statestr)

        try:
            get_device_driver(devnum).switch_power(get_device_addr(devnum), id, state) #
            resp.text = MethodResponse(req).json
        except Exception as ex:
            resp.text = MethodResponse(req,
                            DriverException(0x500, 'Switch.Setswitch failed', ex)).json


@before(PreProcessRequest(maxdev))
class setswitchname:
    def on_put(self, req: Request, resp: Response, devnum: int):
        if not is_connected[devnum]:
            resp.text = MethodResponse(req,
                            NotConnectedException(), None).json
            return

        id = get_id_and_bounds_check(req, resp, devnum)
        if id is None:
            return

        name = get_request_field('Name', req)         # Raises 400 bad request if missing
        ### INTEPRET AS NEEDED OR FAIL ###  # Raise Alpaca InvalidValueException with details!
        try:
            set_device_switch_name(devnum, id, name) #
            resp.text = MethodResponse(req).json
        except Exception as ex:
            resp.text = MethodResponse(req,
                            DriverException(0x500, 'Switch.Setswitchname failed', ex)).json


@before(PreProcessRequest(maxdev))
class setswitchvalue:
    def on_put(self, req: Request, resp: Response, devnum: int):
        if not is_connected[devnum]:
            resp.text = MethodResponse(req,
                            NotConnectedException(), None).json
            return

        id = get_id_and_bounds_check(req, resp, devnum)
        if id is None:
            return

        valuestr = get_request_field('Value', req)      # Raises 400 bad request if missing

        try:
            value = float(valuestr)
            if value > 1.0 or value < 0:
                resp.text = MethodResponse(req,
                                InvalidValueException(f'Value {valuestr} is out of range.')).json
                return
        except:
            resp.text = MethodResponse(req,
                            InvalidValueException(f'Value {valuestr} not a valid number.')).json
            return

        try:
            get_device_driver(devnum).switch_power(get_device_addr(devnum), id, bool(value)) #
            resp.text = MethodResponse(req).json
        except Exception as ex:
            resp.text = MethodResponse(req,
                            DriverException(0x500, 'Switch.Setswitchvalue failed', ex)).json


@before(PreProcessRequest(maxdev))
class canasync:
    def on_get(self, req: Request, resp: Response, devnum: int):
        if not is_connected[devnum]:
            resp.text = PropertyResponse(None, req,
                            NotConnectedException()).json
            return

        id = get_id_and_bounds_check(req, resp, devnum)
        if id is None:
            return

        try:
            val = False # no async implemented
            resp.text = PropertyResponse(val, req).json
        except Exception as ex:
            resp.text = PropertyResponse(None, req,
                            DriverException(0x500, 'Switch.Canasync failed', ex)).json


@before(PreProcessRequest(maxdev))
class statechangecomplete:
    def on_get(self, req: Request, resp: Response, devnum: int):
        id = get_id_and_bounds_check(req, resp, devnum)
        if id is None:
            return

        resp.text = PropertyResponse(None, req,
            NotImplementedException("device cannot async")).json
        return


@before(PreProcessRequest(maxdev))
class cancelasync:
    def on_put(self, req: Request, resp: Response, devnum: int):
        if not is_connected[devnum]:
            resp.text = MethodResponse(req,
                            NotConnectedException(), None).json
            return

        id = get_id_and_bounds_check(req, resp, devnum)
        if id is None:
            return

        try:
            resp.text = MethodResponse(req).json
        except Exception as ex:
            resp.text = MethodResponse(req,
                            DriverException('Switch.Cancelasync failed'), None).json


@before(PreProcessRequest(maxdev))
class setasync:
    def on_put(self, req: Request, resp: Response, devnum: int):
        id = get_id_and_bounds_check(req, resp, devnum)
        if id is None:
            return

        resp.text = MethodResponse(req,
            NotImplementedException("device cannot async"), None).json
        return


@before(PreProcessRequest(maxdev))
class setasyncvalue:
    def on_put(self, req: Request, resp: Response, devnum: int):
        id = get_id_and_bounds_check(req, resp, devnum)
        if id is None:
            return

        resp.text = MethodResponse(req,
            NotImplementedException("device cannot async"), None).json
        return
